[[ONNX]]
arch = "aarch64"
git-tree-sha1 = "b260a0a69a546dea7dd4b2cecce8732115e833e4"
os = "macos"

    [[ONNX.download]]
    sha256 = "a4fb0efaa20f19e98ec6c8f3a21cea92f5e3404c26cc1a182fcaae53bac1e9a7"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.aarch64-apple-darwin.tar.gz"
[[ONNX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5b8885dad72f85d4a765ff4e77df22f20544604"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "61d17a24d70caf6287838c23ebb9ab97f7c504a79483785e6c30ac1c44719d99"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.aarch64-linux-gnu-cxx11.tar.gz"
[[ONNX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d9478ef7f92d72c2d5c3ce4d903938e23fbd46b"
libc = "musl"
os = "linux"

    [[ONNX.download]]
    sha256 = "eeaa3471ba2f1ba049a905718c1a1d1e836456b002f06341a24865e9f4016946"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.aarch64-linux-musl-cxx11.tar.gz"
[[ONNX]]
arch = "aarch64"
git-tree-sha1 = "121c4936104a4e1efa67c440d900a0d9884e4b5e"
os = "freebsd"

    [[ONNX.download]]
    sha256 = "d6954eda46481a2fbc82dd5f8b6e2ed6048050fd7a9ed337d81ca707efdfe192"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.aarch64-unknown-freebsd.tar.gz"
[[ONNX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afa3b85320bd46466c030a8e715bb0c02bd3a8d6"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "703cffb3dedb98796fbf25132e5f5cc28bfb32a61f12ddda8485dae9b068b7e7"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ONNX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d6f656f048a7653b0b09481336727b6d86929b6"
libc = "musl"
os = "linux"

    [[ONNX.download]]
    sha256 = "c62802129b55a2a0fdd3f9652c8aa26e4f6a7978454096afd14f63aa471df091"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ONNX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7292f7e446dd1f5b7055a837f40d4a2a7348afc4"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "ab4811bc34e38d6507509be4b5a3612358cd7a1b622c1e79ff45940389d69869"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ONNX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb68ef5f4dcb2792b42a283843f9e7d3009348f8"
libc = "musl"
os = "linux"

    [[ONNX.download]]
    sha256 = "95ec7d47f742604baa0776e30c1f228ac76ecc548b542c9a60579fe23242e1b9"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ONNX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f69ee9ed053ce8805241e36037f9831d4aea637f"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "4d056a5d76ed565d5dd47423c9bfcd0f3e783c546a751a3fa9c4fb9afe02e741"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.i686-linux-gnu-cxx11.tar.gz"
[[ONNX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b7356b5ff8871ec39b6a23be181cf1c04d872d9"
libc = "musl"
os = "linux"

    [[ONNX.download]]
    sha256 = "52296bdd155bdb01b1b6a62c65459a5e56422566c647f05e27881fa6b98aafb5"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.i686-linux-musl-cxx11.tar.gz"
[[ONNX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "592ef4f0f59c6ce1e19c707f42897d55ad315653"
os = "windows"

    [[ONNX.download]]
    sha256 = "1f9a5219c27430c022dfc40fc7ca5961405699395678c82b22c6e0b13befef0d"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.i686-w64-mingw32-cxx11.tar.gz"
[[ONNX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "caff12c492fba13c12a7068cda4acba1e60a11fb"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "b6c056a0e9bcb04dcfe59b4c4790fd5f55c314d81cc9f5496085035622ca2aba"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ONNX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "049b9a8770d7f5b4ce184643e7d772bd71872cda"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "d7ef1d5df3f9ace8fb3ffb15a9e4bc0975cf6b681a984f5a1f8db39369bbcbb5"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.riscv64-linux-gnu-cxx11.tar.gz"
[[ONNX]]
arch = "x86_64"
git-tree-sha1 = "465a3371bd38269075d49238c2921b4679008396"
os = "macos"

    [[ONNX.download]]
    sha256 = "11a08580ce49ed43403687bd11224ad255c3db1edd510b02286291a9bb4920c5"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.x86_64-apple-darwin.tar.gz"
[[ONNX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea3ddfba3aa595567d98389f6a3c5374ec61b7e4"
libc = "glibc"
os = "linux"

    [[ONNX.download]]
    sha256 = "b8e9f2243e8090bd590c5a8df1270a2b5965085ca071618addf683c7f4f5f144"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.x86_64-linux-gnu-cxx11.tar.gz"
[[ONNX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f15b7fb595586637c9d0be8ea29b5bf8661e862d"
libc = "musl"
os = "linux"

    [[ONNX.download]]
    sha256 = "044db49c87d33dc5243b59f1378726667f4e63c4330731df3f052e8cbb9662a0"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.x86_64-linux-musl-cxx11.tar.gz"
[[ONNX]]
arch = "x86_64"
git-tree-sha1 = "d8468694529970f23f00ecc9d08034a02527c4d6"
os = "freebsd"

    [[ONNX.download]]
    sha256 = "43d27731547982c556d70e5d4331f896ab2d19a66379f35695b0ca99f7ce99cd"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.x86_64-unknown-freebsd.tar.gz"
[[ONNX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4fb30efea68749d380fbf73193571d9b62c6191"
os = "windows"

    [[ONNX.download]]
    sha256 = "3fb73dd33e356229cd2edf1980f82f04676a5f73b871931b6caad3a58d497493"
    url = "https://github.com/JuliaBinaryWrappers/ONNX_jll.jl/releases/download/ONNX-v1.10.2+1/ONNX.v1.10.2.x86_64-w64-mingw32-cxx11.tar.gz"
