# Autogenerated wrapper script for ONNX_jll for aarch64-apple-darwin
export libonnx, libonnxifi, libonnxifi_dummy

using protoc_jll
JLLWrappers.@generate_wrapper_header("ONNX")
JLLWrappers.@declare_file_product(libonnx)
JLLWrappers.@declare_library_product(libonnxifi, "libonnxifi.dylib")
JLLWrappers.@declare_library_product(libonnxifi_dummy, "@rpath/libonnxifi_dummy.dylib")
function __init__()
    JLLWrappers.@generate_init_header(protoc_jll)
    JLLWrappers.@init_file_product(
        libonnx,
        "lib/libonnx.a",
    )

    JLLWrappers.@init_library_product(
        libonnxifi,
        "lib/libonnxifi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi_dummy,
        "lib/libonnxifi_dummy.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
