# Autogenerated wrapper script for ONNX_jll for x86_64-linux-musl-cxx11
export libonnx, libonnx_proto, libonnxifi, libonnxifi_dummy, libonnxifi_loader

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ONNX")
JLLWrappers.@declare_library_product(libonnx, "libonnx.so")
JLLWrappers.@declare_library_product(libonnx_proto, "libonnx_proto.so")
JLLWrappers.@declare_library_product(libonnxifi, "libonnxifi.so")
JLLWrappers.@declare_library_product(libonnxifi_dummy, "libonnxifi_dummy.so")
JLLWrappers.@declare_file_product(libonnxifi_loader)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libonnx,
        "lib/libonnx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnx_proto,
        "lib/libonnx_proto.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi,
        "lib/libonnxifi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi_dummy,
        "lib/libonnxifi_dummy.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libonnxifi_loader,
        "lib/libonnxifi_loader.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
