# Autogenerated wrapper script for ONNX_jll for x86_64-apple-darwin
export libonnx, libonnx_proto, libonnxifi, libonnxifi_dummy, libonnxifi_loader

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ONNX")
JLLWrappers.@declare_library_product(libonnx, "@rpath/libonnx.dylib")
JLLWrappers.@declare_library_product(libonnx_proto, "@rpath/libonnx_proto.dylib")
JLLWrappers.@declare_library_product(libonnxifi, "libonnxifi.dylib")
JLLWrappers.@declare_library_product(libonnxifi_dummy, "@rpath/libonnxifi_dummy.dylib")
JLLWrappers.@declare_file_product(libonnxifi_loader)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libonnx,
        "lib/libonnx.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnx_proto,
        "lib/libonnx_proto.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi,
        "lib/libonnxifi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi_dummy,
        "lib/libonnxifi_dummy.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libonnxifi_loader,
        "lib/libonnxifi_loader.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
