# Autogenerated wrapper script for ONNX_jll for x86_64-w64-mingw32-cxx11
export libonnx, libonnx_proto, libonnxifi, libonnxifi_dummy, libonnxifi_loader

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("ONNX")
JLLWrappers.@declare_library_product(libonnx, "libonnx.dll")
JLLWrappers.@declare_library_product(libonnx_proto, "libonnx_proto.dll")
JLLWrappers.@declare_library_product(libonnxifi, "libonnxifi.dll")
JLLWrappers.@declare_library_product(libonnxifi_dummy, "libonnxifi_dummy.dll")
JLLWrappers.@declare_file_product(libonnxifi_loader)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libonnx,
        "bin\\libonnx.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnx_proto,
        "bin\\libonnx_proto.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi,
        "bin\\libonnxifi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libonnxifi_dummy,
        "bin\\libonnxifi_dummy.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libonnxifi_loader,
        "lib\\libonnxifi_loader.a",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
